name: py39
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.9
  - cpuonly=2.0
  - pytorch==2.5.1
  - torchaudio==2.5.1
  - torchvision==0.20.1
  - pandas==2.2.3
  - scipy==1.13.1
  - numpy==2.0.1
  - networkx==3.2.1
